
version: 2

models:
  - name: customer_stage
    description: '{{doc("customer_stage")}}'
    config:
      materialized: table
      contract:
        enforced: true    
    columns:
      - name: cust_id
        description: '{{doc("customer_cust_id")}}'
        data_type: number(2,0)
        tests:
          - unique
          - not_null
      - name: name
        description: '{{doc("customer_name")}}'
        data_type: varchar(20)
      - name: city
        description: '{{doc("customer_city")}}'
        data_type: varchar(20)
      - name: postcode
        description: '{{doc("customer_postcode")}}'
        data_type: varchar(20)



  - name: product_stage
    description: '{{doc("product_stage")}}'
    columns:
      - name: prod_id
        description: '{{doc("product_prod_id")}}'
        tests:
          - unique
          - not_null
      - name: name
        description: '{{doc("product_name")}}' 
      - name: unit_price
        description: '{{doc("product_unit_price")}}'  



  - name: customer_product_stage
    description: '{{doc("customer_product_stage")}}'
    columns:
      - name: cust_id
        description: '{{doc("customer_cust_id")}}'    
      - name: prod_id
        description: '{{doc("product_prod_id")}}'
      - name: transaction_date
        description: '{{doc("customer_product_transaction_date")}}' 
      - name: units_sold
        description: '{{doc("customer_product_units_sold")}}'