
version: 2

models:
  - name: customer_transfrm
    description: '{{doc("customer_transfrm")}}'
    config:
      materialized: table
      contract:
        enforced: true       
    columns:
      - name: cust_id
        description: '{{doc("customer_cust_id")}}'
        data_type: number(2,0)
      - name: short_description
        description: '{{doc("customer_name")}}'
        data_type: varchar(20)
      - name: city
        description: '{{doc("customer_city")}}'
        data_type: varchar(20)
      - name: postcode
        description: '{{doc("customer_postcode")}}'   
        data_type: varchar(20)



  - name: product_transfrm
    description: '{{doc("product_transfrm")}}'
    config:
      materialized: table
      contract:
        enforced: true       
    columns:
      - name: prod_id
        description: '{{doc("product_prod_id")}}'
        data_type: number(2,0)
      - name: short_description
        description: '{{doc("product_name")}}' 
        data_type: varchar(20)
      - name: unit_price
        description: '{{doc("product_unit_price")}}'  
        data_type: number(10,2)
  


  - name: customer_product_transfrm
    description: '{{doc("customer_product_transfrm")}}'
    config:
      materialized: table
      contract:
        enforced: true      
    columns:
      - name: cust_id
        description: '{{doc("customer_cust_id")}}'    
        data_type: number(2,0)
      - name: prod_id
        description: '{{doc("product_prod_id")}}'
        data_type: number(2,0)
      - name: transaction_date
        description: '{{doc("customer_product_transaction_date")}}' 
        data_type:  date
      - name: units_sold
        description: '{{doc("customer_product_units_sold")}}'  
        data_type: number(2,0)