
version: 2

models:
  - name: customer_stage
    description: "customer_stage dbt model"
    columns:
      - name: cust_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: product_stage
    description: "product_stage dbt model"
    columns:
      - name: prod_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
